#start page 
print("heloo world \n" + "what is ur name?? ")
name = input()
print(("\nHi ") + name + (" ,nice to meet you\n\n\n") + ("what can i help you today " + name))
print("\n\nlets add some numbers\n\n")
a = input("first number  ")
b = input("second number ")
c = input("third number  ")
math = float(a) + float(b) + float(c) 
print("that is ur score " + str(math) +(" ") + (name))
